name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          export PATH="$HOME/.foundry/bin:$PATH"
          foundryup

      - name: Build
        run: |
          export PATH="$HOME/.foundry/bin:$PATH"
          forge build

      - name: Run tests
        run: |
          export PATH="$HOME/.foundry/bin:$PATH"
          forge test -vv
